config/routes.rb
Navarra::Application.routes.draw do
  get "reports/pois"
  get "reports/users"

  get 'locations/cities' => 'locations#cities'
  get 'country/:id/provinces' => 'locations#provinces'
  get 'province/:id/departments' => 'locations#departments'
  get 'department/:id/cities' => 'locations#department_cities'

  get 'poi_types/:id/sub_types' => 'poi_types#sub_types'
  get 'poi_types/:id/chains' => 'poi_types#chains'
  get 'poi_types/:id/food_types' => 'poi_types#food_types'

  get 'configuration' => 'configuration#index'
  put 'configuration/:id' => 'configuration#update', :as => :update_configuration

  resources :pois do
    collection do
      get :download
      get :search
      get :deliver
      get :duplicated
      get :possible_duplicates
    end
  end

  resources :poi_loads, :except => [:edit, :update] do
    collection do
      get :download_xls_example
    end
    member do
      get :download_source_file
      get :download_errors_file
    end
  end

  resources :poi_sub_types
  resources :poi_sources
  resources :street_types
  resources :food_types
  resources :poi_types
  resources :chains
  devise_for :users
  resources :users
  

  root 'pois#index'

  

end

app/controllers/street_types_controller.rb
class StreetTypesController < ApplicationController
  before_filter :new_street_type, :only => [:create]
  load_and_authorize_resource
  before_action :set_street_type, only: [:show, :edit, :update, :destroy]

  # GET /street_types
  # GET /street_types.json
  def index
    @street_types = StreetType.sorted_by_name.paginate(:page => params[:page])
  end

  # GET /street_types/1
  # GET /street_types/1.json
  def show
  end

  # GET /street_types/new
  def new
  end

  # GET /street_types/1/edit
  def edit
  end

  # POST /street_types
  # POST /street_types.json
  def create
    respond_to do |format|
      if @street_type.save
        format.html { redirect_to @street_type, flashman.create_success }
        format.json { render action: 'show', status: :created, location: @street_type }
      else
        flashman.create_fail
        format.html { render action: 'new' }
        format.json { render json: @street_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /street_types/1
  # PATCH/PUT /street_types/1.json
  def update
    respond_to do |format|
      if @street_type.update(street_type_params)
        format.html { redirect_to @street_type, flashman.update_success }
        format.json { head :no_content }
      else
        flashman.update_fail
        format.html { render action: 'edit' }
        format.json { render json: @street_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /street_types/1
  # DELETE /street_types/1.json
  def destroy
    if @street_type.destroy
      flashman.destroy_success
    else
      flashman.destroy_fail @street_type
    end

    respond_to do |format|
      format.html { redirect_to street_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_street_type
      @street_type = StreetType.find(params[:id])
    end

    def new_street_type
      @street_type = StreetType.new(street_type_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def street_type_params
      params.require(:street_type).permit(:name)
    end
end

app/helpers/street_types_helper.rb
module StreetTypesHelper
  def street_types_for_select
    StreetType.sorted_by_name.map { |street_type| [street_type.name, street_type.id] }
  end	
end

app/views/street_types/_form.html.erb
<%= simple_form_for @street_type, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                street_types_path, :class => 'btn' %>
  </div>
<% end %>

app/views/street_types/edit.html.erb
<%- model_class = StreetType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/street_types/index.html.erb
<%- model_class = StreetType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @street_types.each do |street_type| %>
      <tr>
        <td><%= street_type.id %></td>
        <td><%= link_to street_type.name, street_type_path(street_type) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_street_type_path(street_type), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      street_type_path(street_type),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= pager @street_types %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_street_type_path,
            :class => 'btn btn-primary' %>

app/views/street_types/new.html.erb
<%- model_class = StreetType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/street_types/show.html.erb
<%- model_class = StreetType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @street_type.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              street_types_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_street_type_path(@street_type), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              street_type_path(@street_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>