config/routes.rb
Navarra::Application.routes.draw do
  get "reports/pois"
  get "reports/users"

  get 'locations/cities' => 'locations#cities'
  get 'country/:id/provinces' => 'locations#provinces'
  get 'province/:id/departments' => 'locations#departments'
  get 'department/:id/cities' => 'locations#department_cities'

  get 'poi_types/:id/sub_types' => 'poi_types#sub_types'
  get 'poi_types/:id/chains' => 'poi_types#chains'
  get 'poi_types/:id/food_types' => 'poi_types#food_types'

  get 'configuration' => 'configuration#index'
  put 'configuration/:id' => 'configuration#update', :as => :update_configuration

  resources :pois do
    collection do
      get :download
      get :search
      get :deliver
      get :duplicated
      get :possible_duplicates
    end
  end

  resources :poi_loads, :except => [:edit, :update] do
    collection do
      get :download_xls_example
    end
    member do
      get :download_source_file
      get :download_errors_file
    end
  end

  resources :poi_sub_types
  resources :poi_sources
  resources :street_types
  resources :food_types
  resources :poi_types
  resources :chains
  devise_for :users
  resources :users
  

  root 'pois#index'

  

end

app/models/chain.rb
class Chain < ActiveRecord::Base
  belongs_to :poi_type
  has_many :pois

  before_destroy :has_related_pois?

  validates :name, :presence => true
  validates :poi_type_id, :presence => true

  delegate :name, :to => :poi_type, :prefix => true, :allow_nil => true

  def self.sorted_by_name
    self.order(:name)
  end

  def has_related_pois?
    unless Poi.where(:chain_id => self.id).count.zero?
      self.errors.add(:base, :related_pois)
      return false
    end
  end
end

app/controllers/chains_controller.rb
class ChainsController < ApplicationController
  before_filter :new_chain, :only => [:create]
  load_and_authorize_resource
  before_action :set_chain, only: [:show, :edit, :update, :destroy]

  # GET /chains
  # GET /chains.json
  def index
    @chains = Chain.sorted_by_name.paginate(:page => params[:page])
  end

  # GET /chains/1
  # GET /chains/1.json
  def show
  end

  # GET /chains/new
  def new
  end

  # GET /chains/1/edit
  def edit
  end

  # POST /chains
  # POST /chains.json
  def create
    respond_to do |format|
      if @chain.save
        format.html { redirect_to @chain, flashman.create_success }
        format.json { render action: 'show', status: :created, location: @chain }
      else
        flashman.create_fail
        format.html { render action: 'new' }
        format.json { render json: @chain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chains/1
  # PATCH/PUT /chains/1.json
  def update
    respond_to do |format|
      if @chain.update(chain_params)
        format.html { redirect_to @chain, flashman.update_success }
        format.json { head :no_content }
      else
        flashman.update_fail
        format.html { render action: 'edit' }
        format.json { render json: @chain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chains/1
  # DELETE /chains/1.json
  def destroy
    if @chain.destroy
      flashman.destroy_success
    else
      flashman.destroy_fail @chain
    end

    respond_to do |format|
      format.html { redirect_to chains_url }
      format.json { head :no_content }
    end
  end

  private
    def set_chain
      @chain = Chain.find(params[:id])
    end

    def new_chain
      @chain = Chain.new(chain_params)
    end

    def chain_params
      params.require(:chain).permit(:name, :identifier, :poi_type_id)
    end
end

app/helpers/chains_helper.rb
module ChainsHelper
  def chains_for_select
    Chain.sorted_by_name.map { |chain| [chain.name, chain.id] }
  end
end

app/views/chains/_form.html.erb
<%= simple_form_for @chain, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :identifier %>
  <%= f.input :poi_type_id, :collection => poi_types_for_select %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                chains_path, :class => 'btn' %>
  </div>
<% end %>

app/views/chains/edit.html.erb
<%- model_class = Chain -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/chains/index.html.erb
<%- model_class = Chain -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:identifier) %></th>
      <th><%= model_class.human_attribute_name(:poi_type_id) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @chains.each do |chain| %>
      <tr>
        <td><%= chain.id %></td>
        <td><%= link_to chain.name, chain_path(chain) %></td>
        <td><%= chain.identifier %></td>
        <td><%= chain.poi_type_name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_chain_path(chain), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      chain_path(chain),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= pager @chains %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_chain_path,
            :class => 'btn btn-primary' %>

app/views/chains/new.html.erb
<%- model_class = Chain -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/chains/show.html.erb
<%- model_class = Chain -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @chain.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:identifier) %>:</strong></dt>
  <dd><%= @chain.identifier %></dd>
  <dt><strong><%= model_class.human_attribute_name(:poi_type_id) %>:</strong></dt>
  <dd><%= @chain.poi_type_name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              chains_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_chain_path(@chain), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              chain_path(@chain),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>