config/routes.rb
Navarra::Application.routes.draw do
  get "reports/pois"
  get "reports/users"

  get 'locations/cities' => 'locations#cities'
  get 'country/:id/provinces' => 'locations#provinces'
  get 'province/:id/departments' => 'locations#departments'
  get 'department/:id/cities' => 'locations#department_cities'

  get 'poi_types/:id/sub_types' => 'poi_types#sub_types'
  get 'poi_types/:id/chains' => 'poi_types#chains'
  get 'poi_types/:id/food_types' => 'poi_types#food_types'

  get 'configuration' => 'configuration#index'
  put 'configuration/:id' => 'configuration#update', :as => :update_configuration

  resources :pois do
    collection do
      get :download
      get :search
      get :deliver
      get :duplicated
      get :possible_duplicates
    end
  end

  resources :poi_loads, :except => [:edit, :update] do
    collection do
      get :download_xls_example
    end
    member do
      get :download_source_file
      get :download_errors_file
    end
  end

  resources :poi_sub_types
  resources :poi_sources
  resources :street_types
  resources :food_types
  resources :poi_types
  resources :chains
  devise_for :users
  resources :users
  

  root 'pois#index'

  

end

app/models/poi_load.rb
class PoiLoad < ActiveRecord::Base
  require 'fileutils'
  has_many :pois

  validates :name, presence: true, uniqueness: true
  validates :load_date, presence: true
  validates :status, presence: true
  validate :file_exist?
  validate :is_file_type_valid?

  before_create :restart_delayed_job
  before_destroy :restart_delayed_job
  before_destroy :remove_xls_file
  before_destroy :remove_error_file
  after_destroy :remove_unused_lookup_data
  before_save :save_xls_file
  after_save :delay_load_pois_form_xls

  attr_accessor :file

  def self.ordered_by_load_date
    self.order("load_date desc")
  end

  XLS_COLUMNS =[
    :identifier,
    :type,
    :sub_type,
    :name,
    :street_name,
    :street_type,
    :house_number,
    :country,
    :province,
    :department,
    :city,
    :chain,
    :chain_identifier,
    :food_type,
    :phone,
    :email,
    :website,
    :zip,
    :lat,
    :lon,
    :priority,
    :old_identifier
  ]

  def initialize(*args)
    super(*args)
    self.status = :pending
    self.load_date = Time.now
  end

  def source_path
    return nil unless self.directory_name
    "#{self.source_dir}pois.xls"
  end

  def errors_path
    return nil unless self.directory_name
    "#{self.errors_dir}errors.txt"
  end

  def error_file_exist?
    File.exists?(self.errors_path)
  end

  def source_file_exist?
    File.exists?(self.source_path)
  end

  def source_dir
    "#{Rails.public_path.to_s}/poi/loaded_xls/#{self.directory_name}/"
  end

  def errors_dir
    "#{Rails.public_path.to_s}/poi/error_xls/#{self.directory_name}/"
  end

  def remove_xls_file
    if self.source_file_exist?
      FileUtils.rm_rf(self.source_path)
    end    
  end

  def remove_error_file
    if self.error_file_exist?
      FileUtils.rm_rf(self.errors_path)
    end
  end

  def save_xls_file
    directory = Navarra::Xls.save(self.file, "poi/loaded_xls", "pois.xls")
    self.directory_name = directory.split("/").last
    self.success_count = 0
    self.fail_count = 0
    self.already_loaded_count = 0    
  end

  def delay_load_pois_form_xls
    PoiLoad.delay.load_pois_form_xls(self.id)
  end

  def restart_delayed_job
    system "cd #{Rails.root}; rake jobs:clear; bin/delayed_job restart;"
  end

  def remove_unused_lookup_data
    Poi.where(:poi_load_id => self.id).destroy_all
    City.destroy_all
    Department.destroy_all
    Province.destroy_all
    Country.destroy_all
    FoodType.destroy_all
    Chain.destroy_all
    PoiSubType.destroy_all
    PoiType.destroy_all
    StreetType.destroy_all
  end

  def self.load_pois_form_xls poi_load_id
    poi_load = PoiLoad.find(poi_load_id)
    already_loaded_count = 0
    success_count = 0
    fail_count = 0

    begin      
      Navarra::Xls.read(poi_load.source_path) do |sheet, row|
        next if row.idx == 0 #The first row match with the column names
        if PoiLoad.empty_row? row
          poi_load.update_column(:status, :complete)      
          return
        end

        if PoiLoad.poi_already_loaded? row
          already_loaded_count += 1
          poi_load.update_column(:already_loaded_count, already_loaded_count)
        else
          poi = PoiLoad.build_poi(row, poi_load.id)

          if poi.save
            success_count += 1
            poi_load.update_column(:success_count, success_count)
          else
            poi_load.write_error_file(poi.errors.messages, (row.idx + 1))
            fail_count += 1
            poi_load.update_column(:fail_count, fail_count)
          end
        end
      end

      poi_load.update_column(:status, :complete)
    rescue

      poi_load.update_column(:status, :uncomplete)
    end
  end

  def write_error_file errors, row_number
    FileUtils.mkdir(self.errors_dir) unless File.exists?(self.errors_dir)
    File.open(self.errors_path , "a+") do |f|
      f.puts("Fila #{row_number} #{"*"*15}")
      errors.each do |key, values|
        f.puts("#{Poi.human_attribute_name(key, :default => "Error general")}: #{values.join(", ")}\n")
      end
    end
  end

  def self.empty_row? row
    identif = formatted_identifier(row)
    (identif.nil? or identif.empty?)
  end

  def self.poi_already_loaded? row
    !Poi.find_by_identifier(formatted_identifier(row)).nil?
  end

  def self.build_poi row, poi_load_id
    poi_data = {}
    load_poi_identifier(poi_data, row)

    poi_type_id = load_poi_type(poi_data, row)
    load_poi_sub_type(poi_data, poi_type_id, row)
    load_poi_chain(poi_data, poi_type_id, row)
    load_poi_food_type(poi_data, poi_type_id, row)

    load_poi_street_type(poi_data, row)

    country_id = load_poi_country(row)
    province_id = load_poi_province(country_id, row)
    department_id = load_poi_department(province_id, row)
    load_poi_city(poi_data, department_id, row)

    load_geometry(poi_data, row)

    load_poi_old_identifier(poi_data, row)
    load_poi_name(poi_data, row)
    load_poi_street_name(poi_data, row)    
    load_poi_house_number(poi_data, row)
    load_poi_phone(poi_data, row)
    load_poi_email(poi_data, row)
    load_poi_website(poi_data, row)    
    load_poi_priority(poi_data, row)    

    poi_data[:poi_status_id] = PoiStatus.not_validated.id
    poi_data[:poi_source_id] = PoiSource.navteq.id
    poi_data[:active] = true
    poi_data[:deleted] = false
    poi_data[:poi_load_id] = poi_load_id

    Poi.new(poi_data)
  end

  def self.get_xls_column_value column, xls_row
    index = XLS_COLUMNS.find_index column
    return nil unless index
    xls_row[index]
  end

  def file_exist?
    if self.file.nil?
      self.errors.add(:base, :xls_does_not_exist)
      return false
    end
  end

  def is_file_type_valid?
    begin
      valid = (self.file.content_type == "application/vnd.ms-excel")
    rescue
      valid = false
    end
    
    self.errors.add(:base, :invalid_xls_type) unless valid
    valid
  end

  def human_status
    I18n.t("poi_load_statuses.#{self.status.downcase}")
  end

  def self.load_poi_type(poi_data, row)
    poi_type_name = PoiLoad.get_xls_column_value(:type, row)
    poi_type = PoiType.find_or_create_by_name(poi_type_name.to_s)
    return nil unless poi_type
    poi_data[:poi_type_id] = poi_type.id
    poi_type.id
  end

  def self.load_poi_sub_type(poi_data, poi_type_id, row)
    poi_sub_type_name = PoiLoad.get_xls_column_value(:sub_type, row)
    poi_sub_type = PoiSubType.find_or_create_by_name_and_poi_type_id(poi_sub_type_name.to_s, poi_type_id)
    return nil unless poi_sub_type
    poi_data[:poi_sub_type_id] = poi_sub_type.id
  end

  def self.load_poi_chain(poi_data, poi_type_id, row)
    chain_name = PoiLoad.get_xls_column_value(:chain, row)
    chain_identifier = PoiLoad.get_xls_column_value(:chain_identifier, row)
    chain = Chain.find_or_create_by_name_and_poi_type_id(chain_name.to_s, poi_type_id, {:identifier => chain_identifier.to_s})
    return nil unless chain
    poi_data[:chain_id] = chain.id
  end

  def self.load_poi_food_type(poi_data, poi_type_id, row)
    food_type_name = PoiLoad.get_xls_column_value(:food_type, row)
    food_type = FoodType.find_or_create_by_name_and_poi_type_id(food_type_name.to_s, poi_type_id)
    return nil unless food_type
    poi_data[:food_type_id] = food_type.id 
  end

  def self.load_poi_street_type(poi_data, row)
    street_type_name = PoiLoad.get_xls_column_value(:street_type, row)
    street_type = StreetType.find_or_create_by_name(street_type_name.to_s)
    return nil unless street_type
    poi_data[:street_type_id] = street_type.id
  end

  def self.load_poi_country row
    country_name = PoiLoad.get_xls_column_value(:country, row)
    country = Country.find_or_create_by_name(country_name.to_s)
    return nil unless country
    country.id
  end

  def self.load_poi_province(country_id, row)
    province_name = PoiLoad.get_xls_column_value(:province, row)
    province = Province.find_or_create_by_name_and_country_id(province_name.to_s, country_id)
    return nil unless province
    province.id
  end

  def self.load_poi_department(province_id, row)
    department_name = PoiLoad.get_xls_column_value(:department, row)
    department = Department.find_or_create_by_name_and_province_id(department_name.to_s, province_id)
    return nil unless department
    department.id
  end

  def self.load_poi_city(poi_data, department_id, row)
    city_name = PoiLoad.get_xls_column_value(:city, row)
    zip = PoiLoad.get_xls_column_value(:zip, row)
    city = City.find_or_create_by_name_and_department_id(city_name.to_s, department_id, {:zip => zip.to_s})
    return nil unless city
    poi_data[:city_id] = city.id
  end

  def self.load_geometry(poi_data, row)
    poi_data[:latitude] = PoiLoad.get_xls_column_value(:lat, row)
    poi_data[:longitude] = PoiLoad.get_xls_column_value(:lon, row)
  end

  def self.load_poi_name(poi_data, row)
    poi_data[:name] = PoiLoad.get_xls_column_value(:name, row).to_s
  end

  def self.load_poi_street_name(poi_data, row)
    poi_data[:street_name] = PoiLoad.get_xls_column_value(:street_name, row).to_s
  end

  def self.load_poi_house_number(poi_data, row)
    poi_data[:house_number] = PoiLoad.get_xls_column_value(:house_number, row).to_s
  end

  def self.load_poi_identifier(poi_data, row)
    poi_data[:identifier] = formatted_identifier(row)
  end

  def self.formatted_identifier row
    identifier_parts = PoiLoad.get_xls_column_value(:identifier, row).to_s.split("_")
    return nil unless identifier_parts.size == 2
    identifier_parts.last
  end

  def self.load_poi_phone(poi_data, row)
    poi_data[:phone] = PoiLoad.get_xls_column_value(:phone, row).to_s
  end

  def self.load_poi_email(poi_data, row)
    poi_data[:email] = PoiLoad.get_xls_column_value(:email, row).to_s
  end

  def self.load_poi_website(poi_data, row)
    poi_data[:website] = PoiLoad.get_xls_column_value(:website, row).to_s
  end

  def self.load_poi_priority(poi_data, row)
    poi_data[:priority] = PoiLoad.get_xls_column_value(:priority, row).to_i
  end

  def self.load_poi_old_identifier(poi_data, row)

app/controllers/poi_loads_controller.rb
class PoiLoadsController < ApplicationController
  before_filter :new_poi_load, :only => [:create]
  load_and_authorize_resource
  before_action :set_poi_load, only: [:show, :destroy, :download_source_file, :download_errors_file]

  # GET /poi_loads
  # GET /poi_loads.json
  def index
    @poi_loads = PoiLoad.ordered_by_load_date
  end

  # GET /poi_loads/1
  # GET /poi_loads/1.json
  def show
  end

  # GET /poi_loads/new
  def new
  end

  def download_source_file
    begin
      send_file @poi_load.source_path, :type => "application/excel"
    rescue
      render :text => "error"
    end
  end

  def download_xls_example
    send_file "#{Rails.public_path.to_s}/poi/example.xls", :type => "application/excel"
  end

  def download_errors_file
    begin
      send_file @poi_load.errors_path, :type => "text"
    rescue
      render :text => "error"
    end    
  end

  # POST /poi_loads
  # POST /poi_loads.json
  def create
    respond_to do |format|
      if @poi_load.save
        format.html { redirect_to poi_loads_url, flashman.create_success }
        format.json { render action: 'show', status: :created, location: @poi_load }
      else
        flashman.create_fail @poi_load
        format.html { render action: 'new' }
        format.json { render json: @poi_load.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poi_loads/1
  # DELETE /poi_loads/1.json
  def destroy
    if @poi_load.destroy
      flashman.destroy_success
    else
      flashman.destroy_fail @poi_load
    end

    respond_to do |format|
      format.html { redirect_to poi_loads_url }
      format.json { head :no_content }
    end
  end

  private
    def set_poi_load
      @poi_load = PoiLoad.find(params[:id])
    end

    def new_poi_load
      @poi_load = PoiLoad.new(poi_load_params)
    end

    def poi_load_params
      params.require(:poi_load).permit(:name, :load_date, :status, :file)
    end
end

app/helpers/poi_loads_helper.rb
module PoiLoadsHelper
  def render_xls_link poi_load
    if poi_load.source_file_exist?
      return link_to(t("true_value"), download_source_file_poi_load_path(poi_load.id))
    end
    t("false_value")
  end	

  def render_error_link poi_load
    if poi_load.error_file_exist?
      return link_to(t("true_value"), download_errors_file_poi_load_path(poi_load.id))
    end
    t("false_value")
  end

  def poi_load_status_label poi_load
    "<label class='#{poi_load.status.to_s}-status'>#{poi_load.human_status}</label>".html_safe
  end
end

app/views/poi_loads/_form.html.erb
<%= simple_form_for @poi_load, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <%= f.input :name %>
  <%= control_group f.file_field(:file) %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                poi_loads_path, :class => 'btn' %>
  </div>
<% end %>

app/views/poi_loads/index.html.erb
<%- model_class = PoiLoad -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="row-fluid">
  <div class="well span12">
    <h4><%= t("views.poi_load.index.explanation_title") %></h4>
    <%= t("views.poi_load.index.explanation", :link => download_xls_example_poi_loads_path).html_safe %>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>      
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:load_date) %></th>
      <th><%= model_class.human_attribute_name(:success_count) %></th>
      <th><%= model_class.human_attribute_name(:fail_count) %></th>
      <th><%= model_class.human_attribute_name(:already_loaded_count) %></th>
      <th><%= model_class.human_attribute_name(:xls_file_path) %></th>
      <th><%= model_class.human_attribute_name(:error_file_path) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @poi_loads.each do |poi_load| %>
      <tr>
        <td><%= poi_load.id %></td>
        <td><%= link_to poi_load.name, poi_load_path(poi_load) %></td>
        <td><%= l(poi_load.load_date, :format => :long) %></td>
        <td><%= poi_load.success_count %></td>
        <td><%= poi_load.fail_count %></td>
        <td><%= poi_load.already_loaded_count %></td>
        <td><%= render_xls_link poi_load %></td>
        <td><%= render_error_link poi_load %></td>
        <td><%= poi_load_status_label(poi_load) %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      poi_load_path(poi_load),
                      :method => :delete,
                      :data => { :confirm => t('views.poi_load.index.delete_confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_poi_load_path,
            :class => 'btn btn-primary' %>

app/views/poi_loads/new.html.erb
<%- model_class = PoiLoad -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<div class="row-fluid">
  <div class="well span5">
    <h4><%= t("views.poi_load.form.pois_upload_explanation_title") %></h4>
  	<%= t("views.poi_load.form.pois_upload_explanation", :link => download_xls_example_poi_loads_path).html_safe %>
  </div>
</div>
<%= render :partial => 'form' %>

app/views/poi_loads/show.html.erb
<%- model_class = PoiLoad -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @poi_load.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:load_date) %>:</strong></dt>
  <dd><%= l(@poi_load.load_date, :format => :long) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @poi_load.human_status %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              poi_loads_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              poi_load_path(@poi_load),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>