config/routes.rb
Navarra::Application.routes.draw do
  get "reports/pois"
  get "reports/users"

  get 'locations/cities' => 'locations#cities'
  get 'country/:id/provinces' => 'locations#provinces'
  get 'province/:id/departments' => 'locations#departments'
  get 'department/:id/cities' => 'locations#department_cities'

  get 'poi_types/:id/sub_types' => 'poi_types#sub_types'
  get 'poi_types/:id/chains' => 'poi_types#chains'
  get 'poi_types/:id/food_types' => 'poi_types#food_types'

  get 'configuration' => 'configuration#index'
  put 'configuration/:id' => 'configuration#update', :as => :update_configuration

  resources :pois do
    collection do
      get :download
      get :search
      get :deliver
      get :duplicated
      get :possible_duplicates
    end
  end

  resources :poi_loads, :except => [:edit, :update] do
    collection do
      get :download_xls_example
    end
    member do
      get :download_source_file
      get :download_errors_file
    end
  end

  resources :poi_sub_types
  resources :poi_sources
  resources :street_types
  resources :food_types
  resources :poi_types
  resources :chains
  devise_for :users
  resources :users
  

  root 'pois#index'

  

end

app/views/common/_footer.html.erb
<footer class="well">
  &copy; <%= link_to "XoomCode", "http://xoomcode.com/" %> <%= Date.today.year %>
</footer>

app/views/common/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Navarra" %></title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", :media => "all" %>
<%= favicon_link_tag '/favicon.ico', :rel => 'shortcut icon' %>
<%= javascript_include_tag 'application' %>
<% if content_for? :head %>
  <%= yield :head %>
<% end %>

app/views/common/_header.html.erb
<div id="header" class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<%= root_path %>">Navarra</a>
      <div class="container-fluid nav-collapse">
        <ul class="nav pull-right">
          <li>
            <%= select_tag(:poi_select, nil, :class => "input-xxlarge",
              :include_blank => true, :data => {:placeholder => 'Buscar Poi...'}) %>
          </li>    
          <%= nav_item('menu.pois.new', new_poi_path) %>
          <%= nav_item('menu.pois.title', pois_path) %>
          <%= nav_item('menu.pois.duplicated', duplicated_pois_path) %>
          <%= nav_dropdown_item 'menu.reports.title' do %>
            <% nav_item('menu.reports.pois', reports_pois_path) +
            nav_item('menu.reports.users', reports_users_path) %>
          <% end if can?(:visualize, :pois_report) %>
          <% if can?(:index, AppConfiguration) %>
            <%= nav_dropdown_item 'menu.admin.title' do %>
              <% nav_item('menu.admin.app_configuration', configuration_path) +
              nav_item('menu.admin.street_types', street_types_path) +
              nav_item('menu.admin.poi_types', poi_types_path) +
              nav_item('menu.admin.chains', chains_path) +
              nav_item('menu.admin.food_types', food_types_path) +
              nav_item('menu.admin.poi_sub_types', poi_sub_types_path) +
              nav_item('menu.pois.upload', poi_loads_path) +
              nav_item('menu.users', users_path) %>
            <% end %>
          <% else %>
            <%= nav_item('menu.admin.chains', chains_path) %>
          <% end %>          
          <li class="divider-vertical"></li>
          <li><%= link_to current_user.some_identifier, edit_user_path(current_user), class: "login-name"  %></li>
          <li class="divider-vertical"></li>
          <li><%= link_to t('menu.logout'), destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  Navarra.common.poi.initHeaderSearch();
</script>